// import type { Metadata } from "next";
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <>
    <Navbar />
    {/* No desktop a navbar é fixed top-0 (90px); compensa pra não cobrir o conteúdo. */}
    <div className="md:pt-navbar-desktop">{children}</div>
    <Footer />
  </>
  );
}
